name: user_repository
description: A new Flutter package project.
version: 0.0.1
homepage:

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  cloud_firestore: ^2.5.2
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  lumberdash: ^3.0.0
  meta: ^1.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
