name: what_todo
description: A new Flutter project.
homepage: https://github.com/MehadeHassan/what_todo
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  authentication_repository:
    path: packages/authentication_repository
  bloc: ^7.2.0-dev.3
  equatable: ^2.0.3
  firebase_core: ^1.6.0
  flow_builder: ^0.0.4
  flutter:
    sdk: flutter
  flutter_bloc: ^7.2.0
  flutter_svg: ^0.22.0
  formz: ^0.4.0
  formz_validator:
    path: packages/formz_validator
  hydrated_bloc: ^7.0.1
  intl: ^0.17.0
  latim_repository:
    path: packages/latim_repository
  meta: ^1.7.0
  path_provider: ^2.0.3
  todo_repository:
    path: packages/todo_repository
  user_repository:
    path: packages/user_repository


dev_dependencies:
  bloc_test: ^8.1.0
  build_runner: ^2.1.2
  dart_code_metrics: ^4.2.0-dev.3
  flutter_test:
    sdk: flutter
  lumberdash: ^3.0.0
  print_lumberdash: ^3.0.0

flutter:
  uses-material-design: true
