include: all_lint_rules.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "test/.test_coverage.dart"
    - "bin/cache/**"
    - "lib/generated_plugin_registrant.dart"


  strong-mode:
    implicit-casts: false
    implicit-dynamic: false


  errors:
    included_file_warning: ignore
    depend_on_referenced_packages: ignore

  plugins:
    - dart_code_metrics
dart_code_metrics:
  anti-patterns:
    - long-method
    - long-parameter-list
  metrics:
    cyclomatic-complexity: 20
    maximum-nesting-level: 5
    number-of-parameters: 4
    source-lines-of-code: 50

  metrics-exclude:
    - test/**

  rules:
    - newline-before-return
    - no-boolean-literal-compare
    - no-empty-block
    - prefer-trailing-comma
    - prefer-conditional-expressions
    - no-equal-then-else



linter:
  rules:
    public_member_api_docs: false

    # Conflicts with `prefer_single_quotes`
    # Single quotes are easier to type and don't compromise on readability.
    prefer_double_quotes: false

    # Conflicts with `omit_local_variable_types` and other rules.
    # As per Dart guidelines, we want to avoid unnecessary types to make the code
    # more readable.
    # See https://dart.dev/guides/language/effective-dart/design#avoid-type-annotating-initialized-local-variables
    always_specify_types: false

    # conflicts with `always_use_package_imports`
    prefer_relative_imports: false

    # Conflicts with the convention used by flutter, which puts `Key? key`
    # and `required Widget child` last.
    always_put_required_named_parameters_first: false

    # Incompatible with `prefer_final_locals`
    # Having immutable local variables makes larger functions more predictable
    unnecessary_final: false

    lines_longer_than_80_chars: false

