name: formz_validator
description: A new Flutter package project.
version: 0.0.1
homepage:

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  formz: ^0.4.0
  meta: ^1.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
