name: authentication_repository
description: A new Flutter package project.
version: 0.0.1
homepage: https://github.com/MehadeHassan/what_todo
publish_to: none

environment:
  sdk: ">=2.14.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  equatable: ^2.0.3
  firebase_auth: ^3.1.1
  flutter:
    sdk: flutter
  google_sign_in: ^5.1.0
  meta: ^1.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  lumberdash: ^3.0.0
